### PR TITLE
UPDATED: compose version bump to 1.3.1

### PR DESCRIPTION
**Pull request by SlyDen**

### CODE REVIEW

**Comment by SlyDen** [comment]
Wait a minute ... I'm testing version with extra config parameter compose_version - in that implementation user can set exact version in Vagrantfile, so plugin shouldn't be rebuilt each time new version comes

**Comment by SlyDen** [comment]
OK ... I've made smoke test and it was working. E.g. I was able to set 1.2.0 version: vagrant destroy, vagrant up and have docker-compose 1.2.0. If I omit version - it will be 1.3.1 (as default).

```ruby
config.vm.provision :docker_compose, compose_version: "1.2.0"
```

**Comment by leighmcculloch** [comment]
Thanks this looks great!

**Comment by leighmcculloch** [comment]
This has been released in version `v0.0.4`.

**Pull request merged**
